#crear namespace
apiVersion: v1
kind: Namespace
metadata: 
  name: practicamanejadores-namespace
---
#POSTGRESQL
# Volumen persistente 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresdb-vol
  namespace: practicamanejadores-namespace
spec: 
  storageClassName: postgresdb 
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/mnt/postgresdb-vol" 
---
#reclamo de volumen de persistencia
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgresdb
  namespace: practicamanejadores-namespace
spec:
  storageClassName: postgresdb
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 5Gi
---
#storage class postgres
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgresdb
  namespace: practicamanejadores-namespace
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain 
volumeBindingMode: WaitForFirstConsumer
---
#configMap para postgres
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresdb-config 
  namespace: practicamanejadores-namespace
  labels:
    app: postgresdb-server 
data: 
  POSTGRES_USER: root
  POSTGRES_PASSWORD: secret
---
#postgres deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb-deployment
  namespace: practicamanejadores-namespace
  labels:
    app: postgresdb-server
spec:
  selector:
    matchLabels:
      app: postgresdb-server
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresdb-server
    spec:
      containers:
      - image: postgres:11  
        name: postgres-db1
        ports:
        - containerPort: 5432 
          protocol: TCP  
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db-volume
        envFrom:
            - configMapRef:
                name: postgresdb-config
      volumes:
      - name: postgres-db-volume
        persistentVolumeClaim:
          claimName: pvc-postgresdb
---
#servicio para postgres
apiVersion: v1
kind: Service
metadata: 
  name: service-postgresdb
  namespace: practicamanejadores-namespace
spec:
  selector:
    app: postgresdb-server 
  ports:
    - port: 5300 
      targetPort: 5432 
  type: LoadBalancer
---
#MYSQL
#volumen persistente
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysqldb-vol
  namespace: practicamanejadores-namespace  
spec:
  storageClassName: mysqldb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-vol"
---
#reclamo de volumen persistente
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysqldb
  namespace: practicamanejadores-namespace
spec:
  storageClassName: mysqldb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
#storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysqldb
  namespace: practicamanejadores-namespace
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
#config map mysql
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb-config 
  namespace: practicamanejadores-namespace
  labels:
    app: mysqldb-server 
data: 

  MYSQL_ROOT_PASSWORD: secret
---
#deployment mysql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
  namespace: practicamanejadores-namespace
  labels:
    app: mysqldb-server
spec:
  selector:
    matchLabels:
      app: mysqldb-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqldb-server
    spec:
      containers:
      - image: mysql:8.0  #docker pull image
        name: mysql-db1
        ports:
        - containerPort: 3306
          protocol: TCP  
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-db-volume
        envFrom:
            - configMapRef:
                name: mysqldb-config
      volumes:
      - name: mysql-db-volume
        persistentVolumeClaim:
          claimName: pvc-mysqldb 
---
#servicio mysql
apiVersion: v1
kind: Service
metadata: 
  name: service-mysqldb
  namespace: practicamanejadores-namespace
spec:
  selector:
    app: mysqldb-server 
  ports:
    - port: 5303 
      targetPort: 3306
  type: LoadBalancer
---
#MONGO
#volumen persistente
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-vol
  namespace: practicamanejadores-namespace
spec: 
  storageClassName: mongodb 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/mnt/mongodb-vol"
---
#reclamo de volumen persistente
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb
  namespace: practicamanejadores-namespace
spec:
  storageClassName: mongodb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
---
#storage class mongo
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb
  namespace: practicamanejadores-namespace
provisioner: kubernetes.io/no-provisioner 
reclaimPolicy: Retain 
volumeBindingMode: WaitForFirstConsumer
---
#config map mongo
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config 
  namespace: practicamanejadores-namespace
  labels:
    app: mongodb-server 
data: 
  MONGO_USER: root
  MONGO_PASSWORD: secret
---
#deployment mongo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: practicamanejadores-namespace
  labels:
    app: mongodb-server
spec:
  selector:
    matchLabels:
      app: mongodb-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-server
    spec:
      containers:
      - image: mongo:4.0.23  #docker pull image
        name: mongo-db1
        ports:
        - containerPort: 27017
          protocol: TCP  
        volumeMounts:
        - mountPath: /data/db
          name: mongo-db-volume
        envFrom:
            - configMapRef:
                name: mongodb-config
      volumes:
      - name: mongo-db-volume
        persistentVolumeClaim:
          claimName: pvc-mongodb
---
#servicio de mongo
apiVersion: v1
kind: Service
metadata: 
  name: service-mongodb
  namespace: practicamanejadores-namespace
spec:
  selector:
    app: mongodb-server 
  ports:
    - port: 5302 
      targetPort: 27017 
  type: LoadBalancer
---
#REDIS
# Volumen persistente 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redisdb-vol
  namespace: practicamanejadores-namespace  
spec:
  storageClassName: redisdb
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/mnt/redisdb-vol"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redisdb
  namespace: practicamanejadores-namespace
spec:
  storageClassName: redisdb
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 5Gi 
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redisdb
  namespace: practicamanejadores-namespace
provisioner: kubernetes.io/no-provisioner 
reclaimPolicy: Retain 
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redisdb-configmap
  namespace: practicamanejadores-namespace
  labels:
    app: redisdb-server
data:
  REDIS_USER: root
  REDIS_PASSWORD: secret
---
#Hacer deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb-deployment
  namespace: practicamanejadores-namespace
  labels:
    app: redisdb-server
spec:
  selector:
    matchLabels:
      app: redisdb-server
  replicas: 1
  template:
    metadata:
      labels:
        app: redisdb-server
    spec:
      containers:
      - image: redis:6.2.0  #docker pull image
        name: redis-db1
        ports:
        - containerPort: 6379
          protocol: TCP  
        volumeMounts:
        - mountPath: /redis-master-data
          name: redis-db-volume
        envFrom:
            - configMapRef:
                name: redisdb-configmap
      volumes:
      - name: redis-db-volume
        persistentVolumeClaim:
          claimName: pvc-redisdb
---
#Crear servicio
apiVersion: v1
kind: Service
metadata: 
  name: service-redisdb
  namespace: practicamanejadores-namespace
spec:
  selector:
    app: redisdb-server 
  ports:
    - port: 5301
      targetPort: 6379
  type: LoadBalancer